version: "2"
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - mysql
      - redis
      - mongo
    restart: always
    volumes:
      - /www/wwwroot:/usr/share/nginx/html
      - /www/nginxConf:/etc/nginx/conf.d
      - /www/logs:/var/log/nginx
    container_name: nginx 
  php:
    build: ./php
    volumes:
      - /www/wwwroot:/usr/share/nginx/html
    restart: always
    depends_on:
      - mysql
      - redis
    links:
      - mysql
      - redis
      - mongo
    container_name: php
  mysql:
    image: mysql
    volumes:
      - /www/datas/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    container_name: mysql
  mongo:
    image: mongo
    volumes:
      - /www/datas/mongo:/data/db
    ports:
      - "27017:27017"
    container_name: mongo
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
    environment:
        REDIS_PASS_FILE: 123456
    command: [
      "bash", "-c",
      '
       docker-entrypoint.sh
       --requirepass "$$(cat $$REDIS_PASS_FILE)"
      '
    ]
    container_name: redis