version: "2"
services:
  web:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php
    restart: always
    volumes:
      - /Users/fatjiong/Sites:/usr/share/nginx/html
      - /Users/fatjiong/Sites/nginxConf:/etc/nginx/conf.d
      - /Users/fatjiong/Sites/logs:/var/log/nginx
    container_name: nginx 
  php:
    image: php:7.0.27-fpm
    volumes:
      - /Users/fatjiong/Sites:/usr/share/nginx/html
    restart: always
    depends_on:
      - mysql
    container_name: php
  mysql:
    image: mysql
    volumes:
      - /Users/fatjiong/Sites/datas:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    container_name: mysql
  redis:
    image: redis
    ports:
      - "6379:6379"
    container_name: redis