FROM php:7.2.3-fpm

#更新apt-get源 使用163的源
RUN mv /etc/apt/sources.list /etc/apt/sources.list.bak && \
      echo "deb http://mirrors.163.com/debian/ jessie main non-free contrib" >/etc/apt/sources.list && \
       echo "deb http://mirrors.163.com/debian/ jessie-updates main non-free contrib" >>/etc/apt/sources.list && \
       echo "deb http://mirrors.163.com/debian/ jessie-backports main non-free contrib" >>/etc/apt/sources.list && \
       echo "deb-src http://mirrors.163.com/debian/ jessie main non-free contrib" >>/etc/apt/sources.list && \
       echo "deb-src http://mirrors.163.com/debian/ jessie-updates main non-free contrib" >>/etc/apt/sources.list && \
       echo "deb-src http://mirrors.163.com/debian/ jessie-backports main non-free contrib" >>/etc/apt/sources.list && \
       echo "deb http://mirrors.163.com/debian-security/ jessie/updates main non-free contrib" >>/etc/apt/sources.list && \
       echo "deb-src http://mirrors.163.com/debian-security/ jessie/updates main non-free contrib" >>/etc/apt/sources.list

RUN apt-get update -y \
  && apt-get install -y --no-install-recommends libz-dev zlib1g=1:1.2.8.dfsg-2+b1 --allow-downgrades libpng-dev libjpeg-dev libfreetype6-dev libmcrypt-dev libpng-dev libxml2 \
  && docker-php-ext-configure gd \
        --with-freetype-dir=/usr/include/freetype2 \
        --with-png-dir=/usr/include \
        --with-jpeg-dir=/usr/include \
  && docker-php-ext-install mysqli pdo_mysql gd zip opcache iconv mbstring bcmath \
  && docker-php-ext-enable opcache gd \ 
  && pecl install igbinary \
  && pecl install redis \
  && pecl install mongodb \
  && pecl install swoole

COPY ./php.ini /usr/local/etc/php/conf.d/